<a href="https://colab.research.google.com/github/Aish-leksh/Assessment_NumPy-and-Pandas/blob/main/Numpy_and_Pandas_Aiswarya_Lekshmi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q1. NumPy Array Creation

In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.dtype)

[10 20 30 40 50]
(5,)
int64

#Q2. NumPy Array Operations

In [ ]:
arr = np.array([5, 10, 15, 20, 25])

arr_add = arr + 5
print("adding 5:", arr_added)

arr_multiply = arr * 2
print("multiplying by 2:", arr_multiplied)

adding 5: [10 15 20 25 30]
multiplying by 2: [10 20 30 40 50]

#Q3. NumPy Statistical Operations

In [ ]:
arr = np.array([12, 15, 18, 20, 25, 30])
arr_mean = np.mean(arr)
print("Mean:", arr_mean)

arr_median = np.median(arr)
print("Median:", arr_median)

arr_min = np.min(arr)
print("Minimum:", arr_min)

arr_max = np.max(arr)
print("Maximum:", arr_max)

arr_std = np.std(arr)
print("Standard Deviation:", arr_std)

Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard Deviation: 6.027713773341708

#Q4. NumPy Filtering

In [ ]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])
filtered_arr = arr[arr > 40]
print(filtered_arr)

[45 50 65 70]

#Q5. Create a Pandas DataFrame

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'Name': ['Anu', 'Rahul', 'Meera', 'Arun'],
    'Age': [21, 22, 20, 23],
    'Score': [85, 72, 91, 68]
})
print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

#Q6. DataFrame Selection

In [ ]:
print(df[['Name','Score']])
print("\nComplete Record of Meera:\n")
print(df.loc[2])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

Complete Record of Meera:

Name     Meera
Age         20
Score       91
Name: 2, dtype: object

#Q7. DataFrame Filtering

In [ ]:
filtered_df = df[df['Score'] > 75]
print(filtered_df)

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

#Q8. DataFrame Inspection

In [ ]:
print("Number of rows and columns:", df.shape)
print("\nColumn names:", df.columns)
print("\nData types:", df.dtypes)
print("\nBasic statistical summary:\n", df.describe)

Number of rows and columns: (4, 3)

Column names: Index(['Name', 'Age', 'Score'], dtype='object')

Data types: Name     object
Age       int64
Score     int64
dtype: object

Basic statistical summary:
 <bound method NDFrame.describe of     Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68>

#Q9. Sorting a DataFrame

In [ ]:
print("Score in Descending order:\n")
sorted_df = df.sort_values(by='Score', ascending=False)
print(sorted_df)

Score in Descending order:

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

#Q10. Handling Missing Values

In [ ]:
print("Missing values:")
print(df.isnull())

mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)

mean_score = df['Score'].mean()
df['Score'] = df['Score'].fillna(mean_score)

print("\nDataFrame after replacing missing values:")
print(df)

Missing values:
    Name    Age  Score
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

DataFrame after replacing missing values:
  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

#SECTION - B

In [ ]:
# to read the csv file
df = pd.read_csv('/content/drive/MyDrive/DSAB13/Assessment/student_performance.csv')
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

#Q11. Data Loading and Exploration

In [ ]:
print("First 5 records:")
print(df.head())

print("\nLast 5 records:")
print(df.tail())

print("\nNumber of rows and columns:", df.shape)

print("\nColumn names:", df.columns)

print("\nData types:")
print(df.dtypes)

print("\nStatistical summary of numerical columns:")
print(df.describe())

First 5 records:
  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9

Last 5 records:
   Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

Number of rows and columns: (80, 11)

Column names: Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

Data types:
Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

Statistical summary of numerical columns:
             Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  77.000000   77.000000     78.000000   80.000000     78.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.155126   10.054204     16.722103   14.630417     15.814294
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   75.500000     64.525000   60.650000     61.800000
50%    22.000000   81.100000     72.000000   69.300000     70.000000
75%    24.000000   86.400000     86.525000   81.150000     82.575000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score
count    78.000000    78.000000
mean     68.574359    70.696154
std      16.417242    14.053871
min      25.000000    40.600000
25%      57.175000    60.450000
50%      70.700000    70.950000
75%      80.650000    82.275000
max     100.000000    97.000000

#Q12. Filtering and Sorting

In [ ]:
print("Students with Final_Score > 75:")
print(df[df['Final_Score'] > 75])

print("\nStudents with Attendance < 75%:")
print(df[df['Attendance'] < 75])

print("\nStudents from Data Science department with Final_Score > 80:")
print(df[(df['Department'] == 'Data Science') & (df['Final_Score'] > 80)])

print("\nStudents sorted by Final_Score (highest to lowest):")
print(df.sort_values(by='Final_Score', ascending=False))

Students with Final_Score > 75:
   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

Students with Attendance < 75%:
   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

Students from Data Science department with Final_Score > 80:
   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

Students sorted by Final_Score (highest to lowest):
   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

#Q13. Feature Creation

In [ ]:
df['Average_Technical_Score'] = (df['Python_Score'] +
                                 df['SQL_Score'] +
                                 df['Pandas_Score'] +
                                 df['NumPy_Score']) / 4
conditions = [
    (df['Average_Technical_Score'] >= 90),
    (df['Average_Technical_Score'] >= 75),
    (df['Average_Technical_Score'] >= 60)
]
choices = ['Excellent', 'Good', 'Average']

df['Performance'] = np.select(conditions, choices, default='Needs Improvement')

df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

#Q14. GroupBy Analysis

In [ ]:
print("Number of students:")
print(df.groupby('Department').size())

print("\nAverage Final Score:")
print(df.groupby('Department')['Final_Score'].mean())

print("\nMaximum Final Score:")
print(df.groupby('Department')['Final_Score'].max())

print("\nMinimum Final Score:")
print(df.groupby('Department')['Final_Score'].min())

print("\nSorted DataFrame:")
print(df.groupby('Department')['Final_Score'].mean().sort_values(ascending=False))

Number of students:
Department
 Data Science        1
Commerce             8
Computer Science    29
Computer science     1
Data Science        27
Electronics         13
data science         1
dtype: int64

Average Final Score:
Department
 Data Science       55.100000
Commerce            67.825000
Computer Science    71.479310
Computer science    46.700000
Data Science        71.324000
Electronics         72.846154
data science        66.900000
Name: Final_Score, dtype: float64

Maximum Final Score:
Department
 Data Science       55.1
Commerce            83.7
Computer Science    96.0
Computer science    46.7
Data Science        97.0
Electronics         86.9
data science        66.9
Name: Final_Score, dtype: float64

Minimum Final Score:
Department
 Data Science       55.1
Commerce            54.6
Computer Science    40.6
Computer science    46.7
Data Science        43.5
Electronics         51.2
data science        66.9
Name: Final_Score, dtype: float64

Sorted DataFrame:
Department
Electronics         72.846154
Computer Science    71.479310
Data Science        71.324000
Commerce            67.825000
data science        66.900000
 Data Science       55.100000
Computer science    46.700000
Name: Final_Score, dtype: float64

#Q15. NumPy and Pandas Integration

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/DSAB13/Assessment/student_performance.csv')
final_scores = df['Final_Score'].dropna().to_numpy()

mean_val = np.mean(final_scores)
median_val = np.median(final_scores)
std_val = np.std(final_scores)
p25 = np.percentile(final_scores, 25)
p75 = np.percentile(final_scores, 75)

print(f"Mean: {mean_val:.2f}")
print(f"Median: {median_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")
print(f"25th Percentile: {p25:.2f}")
print(f"75th Percentile: {p75:.2f}")

students_above_mean = df[df['Final_Score'] > mean_val]
print(
    f"\nNumber of students above mean: {len(students_above_mean)}"
)
students_above_mean[['Name', 'Final_Score']]

Mean: 70.70
Median: 70.95
Standard Deviation: 13.96
25th Percentile: 60.45
75th Percentile: 82.28

Number of students above mean: 42

              Name  Final_Score
0      Rahul Varma         82.7
4        Asha Nair         81.9
6      Akhil Varma         77.0
7      Akhil Varma         79.2
8       Diya Menon         83.0
9     Gokul Pillai         73.8
10        Diya Das         91.9
11      Arun Reddy         86.9
16    Rahul Thomas         91.1
17      Priya Nair         75.1
20      Arun Varma         73.2
23  Fathima Joseph         83.7
24     Kiran Varma         77.3
27     Nikhil Nair         77.1
30      Amal Varma         85.5
33        Amal Das         84.3
35      Maya Menon         84.2
37    Kiran Pillai         82.4
39    Rohan Sharma         78.5
40     Amal Pillai         94.5
41     Arun Joseph         77.9
43       Rahul Das         77.3
46       Gokul Das         74.8
47     Priya Kumar         77.3
48     Asha Sharma         97.0
51      Gokul Nair         79.3
52      Maya Varma         71.0
55     Vivek Varma         93.3
56    Rohan Pillai         75.2
57     Diya Thomas         92.3
58       Anu Menon         84.9
59      Asha Menon         87.9
60  Fathima Sharma         70.8
61    Kiran Pillai         96.0
64    Rohan Sharma         83.5
66    Rahul Thomas         70.7
67        Maya Das         83.7
72   Swathi Joseph         73.5
73       Anu Kumar         83.4
74      Gokul Nair         70.9
77  Fathima Sharma         75.2
79      Diya Varma         78.6

#SECTION C – HARD

#Q16. Student Performance Analysis

Use student_performance.csv .
A. Data Cleaning – 2 Marks
Identify missing values.
Handle missing numerical values appropriately.

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/MyDrive/DSAB13/Assessment/student_performance.csv")

print("Missing values:")
print(df.isnull().sum())

numerical_cols = df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

print("\nMissing values per column after filling numerical missing values:")
print(df.isnull().sum())

df

df['Average_Score'] = (df['Python_Score']+
                       df['SQL_Score']+
                       df['Pandas_Score']+
                       df['NumPy_Score'])/4

df['Pass_Status'] = np.where(df['Average_Score'] >= 50, 'Pass', 'Fail')


print(df)

print(df.sort_values(by='Average_Score', ascending=False).head(5))

dept_avg = df.groupby('Department')['Average_Score'].mean()
print(dept_avg.idxmax(), dept_avg.max())

print(df.groupby('Department')['Attendance'].mean())

print(df['Pass_Status'].value_counts())

summary = df.groupby('Department').agg(
    Total_Students=('Department', 'count'),
    Average_Score=('Average_Score', 'mean'),
    Average_Attendance=('Attendance', 'mean'),
    Pass_Count=('Pass_Status', lambda x: (x == 'Pass').sum()),
    Fail_Count=('Pass_Status', lambda x: (x == 'Fail').sum())
).reset_index()

print(summary)

Missing values:
Student_ID      0
Name            0
Gender          0
Department      0
Age             3
Attendance      3
Python_Score    2
SQL_Score       0
Pandas_Score    2
NumPy_Score     2
Final_Score     2
dtype: int64

Missing values per column after filling numerical missing values:
Student_ID      0
Name            0
Gender          0
Department      0
Age             0
Attendance      0
Python_Score    0
SQL_Score       0
Pandas_Score    0
NumPy_Score     0
Final_Score     0
dtype: int64
   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score  Average_Score Pass_Status
0          82.7         83.575        Pass
1          60.3         65.200        Pass
2          67.1         73.400        Pass
3          57.2         54.475        Pass
4          81.9         83.275        Pass
..          ...            ...         ...
75         47.2         47.775        Fail
76         43.5         46.525        Fail
77         75.2         80.250        Pass
78         63.4         61.350        Pass
79         78.6         77.075        Pass

[80 rows x 13 columns]
   Student_ID          Name  Gender        Department   Age  Attendance  \
10    STU1011      Diya Das  Female      Data Science  20.0       100.0
61    STU1062  Kiran Pillai  Female  Computer Science  19.0        83.8
8     STU1009    Diya Menon    Male      Data Science  25.0        64.4
16    STU1017  Rahul Thomas  Female      Data Science  25.0        78.3
35    STU1036    Maya Menon  Female       Electronics  19.0        82.0

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
10         100.0       93.2         100.0         89.3         91.9
61         100.0      100.0          89.4         91.4         96.0
8           94.8       86.0          87.7        100.0         83.0
16          80.8       99.4          77.2        100.0         91.1
35          95.3       93.4         100.0         62.5         84.2

    Average_Score Pass_Status
10         95.625        Pass
61         95.200        Pass
8          92.125        Pass
16         89.350        Pass
35         87.800        Pass
Electronics 74.06346153846154
Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.768025
Computer science    92.100000
Data Science        82.076768
Electronics         80.576923
data science        81.672727
Name: Attendance, dtype: float64
Pass_Status
Pass    72
Fail     8
Name: count, dtype: int64
         Department  Total_Students  Average_Score  Average_Attendance  \
0     Data Science                1      59.200000           76.700000
1          Commerce               8      68.806931           77.437500
2  Computer Science              29      70.515296           82.768025
3  Computer science               1      53.843590           92.100000
4      Data Science              27      70.671783           82.076768
5       Electronics              13      74.063462           80.576923
6      data science               1      64.725000           81.672727

   Pass_Count  Fail_Count
0           1           0
1           8           0
2          24           5
3           1           0
4          24           3
5          13           0
6           1           0

#Q18. Advanced NumPy and Pandas Analysis

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/DSAB13/Assessment/employee.csv')

df['Salary'] = df['Salary'].astype(str).str.replace(',', '', regex=True)
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

df['Experience'] = pd.to_numeric(df['Experience'], errors='coerce')


df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Performance_Score'] = df['Performance_Score'].fillna(df['Performance_Score'].mean())
df['Experience'] = df['Experience'].fillna(df['Experience'].mean())

salary = df['Salary'].to_numpy()
performance = df['Performance_Score'].to_numpy()

print("Mean Salary:", np.mean(salary))
print("Median Salary:", np.median(salary))
print("Std Dev of Salary:", np.std(salary))
print("Mean Performance Score:", np.mean(performance))

filtered = df[(df['Experience'] > 3) & (df['Performance_Score'] >= 80)]
print("\nFiltered Employees (Experience > 3 and Performance >= 80):")
print(filtered)

dept = df.groupby('Department').agg(
    Average_Salary=('Salary', 'mean'),
    Average_Performance_Score=('Performance_Score', 'mean'),
    Total_Projects_Completed=('Projects_Completed', 'sum'),
    Number_of_Employees=('Employee_ID', 'count')
)
print("\nDepartment Aggregations:")
print(dept)

print("\nTop Department by Performance Score:", dept['Average_Performance_Score'].idxmax())

result = df[(df['Salary'] > np.mean(salary)) &
            (df['Performance_Score'] > np.mean(performance))]
print("\nEmployees with above-average Salary and Performance:")
print(result[['Employee_ID', 'Department', 'Salary', 'Performance_Score']])

Mean Salary: 61054.98611111111
Median Salary: 61142.0
Std Dev of Salary: 17780.063072623827
Mean Performance Score: 71.013698630137

Filtered Employees (Experience > 3 and Performance >= 80):
   Employee_ID            Department  Experience   Salary  Performance_Score  \
1      EMP2002  Software Development    8.700000  78243.0               85.6
6      EMP2007                    HR    4.600000  51328.0               91.0
17     EMP2018  Software development    5.600000  79595.0               83.0
22     EMP2023        Data Analytics    5.700000  83674.0               81.0
25     EMP2026      Data Engineering    5.800000  45336.0               88.0
26     EMP2027  Software Development    8.100000  74816.0               84.3
30     EMP2031  Software Development    6.900000  60930.0               94.4
31     EMP2032            IT Support    4.700000  65566.0               85.7
45     EMP2046  Software Development    3.400000  51056.0               92.8
48     EMP2049      Data Engineering    4.700000  43341.0               82.2
49     EMP2050  Software Development    4.900000  68620.0               90.9
53     EMP2054                    HR    4.620833  62522.0               82.1
57     EMP2058                    HR    5.300000  68152.0               81.1
58     EMP2059      Data Engineering    3.800000  52079.0               84.1
62     EMP2063  Software Development    7.000000  74892.0               88.0
65     EMP2066  Software Development    5.900000  82567.0               81.1
69     EMP2070            IT Support    3.100000  60755.0               83.4
72     EMP2073      Data Engineering    8.300000  83685.0               87.4
74     EMP2075  Software Development   10.100000  98224.0               83.6

    Projects_Completed
1                 11.0
6                  0.0
17                 9.0
22                12.0
25                 NaN
26                19.0
30                 6.0
31                 6.0
45                 2.0
48                 5.0
49                11.0
53                13.0
57                 6.0
58                 7.0
62                15.0
65                10.0
69                 1.0
72                16.0
74                13.0

Department Aggregations:
                      Average_Salary  Average_Performance_Score  \
Department
 data analytics         46324.000000                  73.800000
Data Analytics          58446.822712                  67.176471
Data Engineering        60182.614316                  72.130769
HR                      63136.300000                  64.900000
IT Support              63862.569444                  70.501957
Software Development    61269.840000                  74.776548
Software development    79595.000000                  83.000000

                      Total_Projects_Completed  Number_of_Employees
Department
 data analytics                            6.0                    1
Data Analytics                           108.0                   17
Data Engineering                          73.0                   13
HR                                        47.0                   10
IT Support                                30.0                    7
Software Development                     190.0                   25
Software development                       9.0                    1

Top Department by Performance Score: Software development

Employees with above-average Salary and Performance:
   Employee_ID            Department    Salary  Performance_Score
1      EMP2002  Software Development   78243.0               85.6
3      EMP2004        Data Analytics   65088.0               78.5
5      EMP2006      Data Engineering   62749.0               72.2
17     EMP2018  Software development   79595.0               83.0
20     EMP2021      Data Engineering   69207.0               71.1
22     EMP2023        Data Analytics   83674.0               81.0
23     EMP2024            IT Support  109642.0               76.0
26     EMP2027  Software Development   74816.0               84.3
28     EMP2029  Software Development   65579.0               78.8
31     EMP2032            IT Support   65566.0               85.7
36     EMP2037      Data Engineering   73192.0               72.8
49     EMP2050  Software Development   68620.0               90.9
53     EMP2054                    HR   62522.0               82.1
55     EMP2056  Software Development   63338.0               75.3
57     EMP2058                    HR   68152.0               81.1
59     EMP2060        Data Analytics   99744.0               72.5
62     EMP2063  Software Development   74892.0               88.0
65     EMP2066  Software Development   82567.0               81.1
70     EMP2071                   NaN   67088.0               77.6
72     EMP2073      Data Engineering   83685.0               87.4
74     EMP2075  Software Development   98224.0               83.6