<a href="https://colab.research.google.com/github/Aish-leksh/Assessment_NumPy-and-Pandas/blob/main/Numpy_and_Pandas_Aiswarya_Lekshmi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q1. NumPy Array Creation

In [5]:
import numpy as np

In [4]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.dtype)

[10 20 30 40 50]
(5,)
int64

#Q2. NumPy Array Operations

In [34]:
arr = np.array([5, 10, 15, 20, 25])

arr_add = arr + 5
print("adding 5:", arr_added)

arr_multiply = arr * 2
print("multiplying by 2:", arr_multiplied)

adding 5: [10 15 20 25 30]
multiplying by 2: [10 20 30 40 50]

#Q3. NumPy Statistical Operations

In [8]:
arr = np.array([12, 15, 18, 20, 25, 30])
arr_mean = np.mean(arr)
print("Mean:", arr_mean)

arr_median = np.median(arr)
print("Median:", arr_median)

arr_min = np.min(arr)
print("Minimum:", arr_min)

arr_max = np.max(arr)
print("Maximum:", arr_max)

arr_std = np.std(arr)
print("Standard Deviation:", arr_std)

Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard Deviation: 6.027713773341708

#Q4. NumPy Filtering

In [9]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])
filtered_arr = arr[arr > 40]
print(filtered_arr)

[45 50 65 70]

#Q5. Create a Pandas DataFrame

In [11]:
import pandas as pd

In [13]:
df = pd.DataFrame({
    'Name': ['Anu', 'Rahul', 'Meera', 'Arun'],
    'Age': [21, 22, 20, 23],
    'Score': [85, 72, 91, 68]
})
print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

#Q6. DataFrame Selection

In [17]:
print(df[['Name','Score']])
print("\nComplete Record of Meera:\n")
print(df.loc[2])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

Complete Record of Meera:

Name     Meera
Age         20
Score       91
Name: 2, dtype: object

#Q7. DataFrame Filtering

In [23]:
filtered_df = df[df['Score'] > 75]
print(filtered_df)

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

#Q8. DataFrame Inspection

In [24]:
print("Number of rows and columns:", df.shape)
print("\nColumn names:", df.columns)
print("\nData types:", df.dtypes)
print("\nBasic statistical summary:\n", df.describe)

Number of rows and columns: (4, 3)

Column names: Index(['Name', 'Age', 'Score'], dtype='object')

Data types: Name     object
Age       int64
Score     int64
dtype: object

Basic statistical summary:
 <bound method NDFrame.describe of     Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68>

#Q9. Sorting a DataFrame

In [27]:
print("Score in Descending order:\n")
sorted_df = df.sort_values(by='Score', ascending=False)
print(sorted_df)

Score in Descending order:

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

#Q10. Handling Missing Values

In [30]:
print("Missing values:")
print(df.isnull())

mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)

mean_score = df['Score'].mean()
df['Score'] = df['Score'].fillna(mean_score)

print("\nDataFrame after replacing missing values:")
print(df)

Missing values:
    Name    Age  Score
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

DataFrame after replacing missing values:
  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

#SECTION - B

In [31]:
# to read the csv file
df = pd.read_csv('/content/drive/MyDrive/DSAB13/Assessment/student_performance.csv')
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

#Q11. Data Loading and Exploration

In [35]:
print("First 5 records:")
print(df.head())

print("\nLast 5 records:")
print(df.tail())

print("\nNumber of rows and columns:", df.shape)

print("\nColumn names:", df.columns)

print("\nData types:")
print(df.dtypes)

print("\nStatistical summary of numerical columns:")
print(df.describe())

First 5 records:
  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9

Last 5 records:
   Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

Number of rows and columns: (80, 11)

Column names: Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

Data types:
Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

Statistical summary of numerical columns:
             Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  77.000000   77.000000     78.000000   80.000000     78.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.155126   10.054204     16.722103   14.630417     15.814294
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   75.500000     64.525000   60.650000     61.800000
50%    22.000000   81.100000     72.000000   69.300000     70.000000
75%    24.000000   86.400000     86.525000   81.150000     82.575000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score
count    78.000000    78.000000
mean     68.574359    70.696154
std      16.417242    14.053871
min      25.000000    40.600000
25%      57.175000    60.450000
50%      70.700000    70.950000
75%      80.650000    82.275000
max     100.000000    97.000000

#Q12. Filtering and Sorting

In [36]:
print("Students with Final_Score > 75:")
print(df[df['Final_Score'] > 75])

print("\nStudents with Attendance < 75%:")
print(df[df['Attendance'] < 75])

print("\nStudents from Data Science department with Final_Score > 80:")
print(df[(df['Department'] == 'Data Science') & (df['Final_Score'] > 80)])

print("\nStudents sorted by Final_Score (highest to lowest):")
print(df.sort_values(by='Final_Score', ascending=False))

Students with Final_Score > 75:
   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

Students with Attendance < 75%:
   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

Students from Data Science department with Final_Score > 80:
   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

Students sorted by Final_Score (highest to lowest):
   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

#Q13. Feature Creation

In [38]:
df['Average_Technical_Score'] = (df['Python_Score'] +
                                 df['SQL_Score'] +
                                 df['Pandas_Score'] +
                                 df['NumPy_Score']) / 4
conditions = [
    (df['Average_Technical_Score'] >= 90),
    (df['Average_Technical_Score'] >= 75),
    (df['Average_Technical_Score'] >= 60)
]
choices = ['Excellent', 'Good', 'Average']

df['Performance'] = np.select(conditions, choices, default='Needs Improvement')

df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

#Q14. GroupBy Analysis

In [39]:
print("Number of students:")
print(df.groupby('Department').size())

print("\nAverage Final Score:")
print(df.groupby('Department')['Final_Score'].mean())

print("\nMaximum Final Score:")
print(df.groupby('Department')['Final_Score'].max())

print("\nMinimum Final Score:")
print(df.groupby('Department')['Final_Score'].min())

print("\nSorted DataFrame:")
print(df.groupby('Department')['Final_Score'].mean().sort_values(ascending=False))

Number of students:
Department
 Data Science        1
Commerce             8
Computer Science    29
Computer science     1
Data Science        27
Electronics         13
data science         1
dtype: int64

Average Final Score:
Department
 Data Science       55.100000
Commerce            67.825000
Computer Science    71.479310
Computer science    46.700000
Data Science        71.324000
Electronics         72.846154
data science        66.900000
Name: Final_Score, dtype: float64

Maximum Final Score:
Department
 Data Science       55.1
Commerce            83.7
Computer Science    96.0
Computer science    46.7
Data Science        97.0
Electronics         86.9
data science        66.9
Name: Final_Score, dtype: float64

Minimum Final Score:
Department
 Data Science       55.1
Commerce            54.6
Computer Science    40.6
Computer science    46.7
Data Science        43.5
Electronics         51.2
data science        66.9
Name: Final_Score, dtype: float64

Sorted DataFrame:
Department
Electronics         72.846154
Computer Science    71.479310
Data Science        71.324000
Commerce            67.825000
data science        66.900000
 Data Science       55.100000
Computer science    46.700000
Name: Final_Score, dtype: float64

#Q15. NumPy and Pandas Integration

In [43]:
df = pd.read_csv('/content/drive/MyDrive/DSAB13/Assessment/student_performance.csv')
final_scores = df['Final_Score'].dropna().to_numpy()

mean_val = np.mean(final_scores)
median_val = np.median(final_scores)
std_val = np.std(final_scores)
p25 = np.percentile(final_scores, 25)
p75 = np.percentile(final_scores, 75)

print(f"Mean: {mean_val:.2f}")
print(f"Median: {median_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")
print(f"25th Percentile: {p25:.2f}")
print(f"75th Percentile: {p75:.2f}")

students_above_mean = df[df['Final_Score'] > mean_val]
print(
    f"\nNumber of students above mean: {len(students_above_mean)}"
)
students_above_mean[['Name', 'Final_Score']]

Mean: 70.70
Median: 70.95
Standard Deviation: 13.96
25th Percentile: 60.45
75th Percentile: 82.28

Number of students above mean: 42

              Name  Final_Score
0      Rahul Varma         82.7
4        Asha Nair         81.9
6      Akhil Varma         77.0
7      Akhil Varma         79.2
8       Diya Menon         83.0
9     Gokul Pillai         73.8
10        Diya Das         91.9
11      Arun Reddy         86.9
16    Rahul Thomas         91.1
17      Priya Nair         75.1
20      Arun Varma         73.2
23  Fathima Joseph         83.7
24     Kiran Varma         77.3
27     Nikhil Nair         77.1
30      Amal Varma         85.5
33        Amal Das         84.3
35      Maya Menon         84.2
37    Kiran Pillai         82.4
39    Rohan Sharma         78.5
40     Amal Pillai         94.5
41     Arun Joseph         77.9
43       Rahul Das         77.3
46       Gokul Das         74.8
47     Priya Kumar         77.3
48     Asha Sharma         97.0
51      Gokul Nair         79.3
52      Maya Varma         71.0
55     Vivek Varma         93.3
56    Rohan Pillai         75.2
57     Diya Thomas         92.3
58       Anu Menon         84.9
59      Asha Menon         87.9
60  Fathima Sharma         70.8
61    Kiran Pillai         96.0
64    Rohan Sharma         83.5
66    Rahul Thomas         70.7
67        Maya Das         83.7
72   Swathi Joseph         73.5
73       Anu Kumar         83.4
74      Gokul Nair         70.9
77  Fathima Sharma         75.2
79      Diya Varma         78.6

#SECTION C – HARD

#Q16. Student Performance Analysis

Use student_performance.csv .
A. Data Cleaning – 2 Marks
Identify missing values.
Handle missing numerical values appropriately.

In [52]:
df = pd.read_csv("/content/drive/MyDrive/DSAB13/Assessment/student_performance.csv")

print("Missing values:")
print(df.isnull().sum())

numerical_cols = df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

print("\nMissing values per column after filling numerical missing values:")
print(df.isnull().sum())

df

df['Average_Score'] = (df['Python_Score']+
                       df['SQL_Score']+
                       df['Pandas_Score']+
                       df['NumPy_Score'])/4

df['Pass_Status'] = np.where(df['Average_Score'] >= 50, 'Pass', 'Fail')


print(df)

#df.head(Average_Score)

Missing values:
Student_ID      0
Name            0
Gender          0
Department      0
Age             3
Attendance      3
Python_Score    2
SQL_Score       0
Pandas_Score    2
NumPy_Score     2
Final_Score     2
dtype: int64

Missing values per column after filling numerical missing values:
Student_ID      0
Name            0
Gender          0
Department      0
Age             0
Attendance      0
Python_Score    0
SQL_Score       0
Pandas_Score    0
NumPy_Score     0
Final_Score     0
dtype: int64
   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score  Average_Score Pass_Status
0          82.7         83.575        Pass
1          60.3         65.200        Pass
2          67.1         73.400        Pass
3          57.2         54.475        Pass
4          81.9         83.275        Pass
..          ...            ...         ...
75         47.2         47.775        Fail
76         43.5         46.525        Fail
77         75.2         80.250        Pass
78         63.4         61.350        Pass
79         78.6         77.075        Pass

[80 rows x 13 columns]

#Q17. Sales Data Analysis

In [54]:
df = pd.read_csv("/content/drive/MyDrive/DSAB13/Assessment/sales.csv")
df

,Order_ID,Order_Date,Product,Category,Region,Sales,Quantity,Discount,Profit
0,ORD5001,2026-06-10,Office Chair,Furniture,East,142.1,1.0,0.02,12.78
1,ORD5002,2026-04-25,USB Hub,Accessories,North,51.52,2.0,0.08,4.57
2,ORD5003,2026-03-07,Monitor,Computers,West,648.0,4.0,0.1,86.32
3,ORD5004,2026-03-19,Office Chair,Furniture,North,290.0,2.0,0.0,47.77
4,ORD5005,2026-01-25,Tablet,Computers,North,304.0,1.0,0.05,23.43
...,...,...,...,...,...,...,...,...,...
175,ORD5176,2026-05-02,External SSD,Storage,North,418.0,4.0,0.05,80.35
176,ORD5177,2026-01-30,Headphones,Accessories,North,308.75,5.0,0.05,86.16
177,ORD5178,2026-03-20,USB Hub,Accessories,South,166.6,7.0,0.15,28.42
178,ORD5179,2026-05-27,USB Hub,Accessories,South,89.6,4.0,0.2,15.18
179,ORD5180,2026-02-11,Wireless Mouse,Accessories,West,56.1,3.0,0.15,16.83

In [60]:
import pandas as pd
import numpy as np

sales_df = pd.read_csv("/content/drive/MyDrive/DSAB13/Assessment/sales.csv")

# Clean Sales column: remove commas and convert to numeric
sales_df['Sales'] = sales_df['Sales'].astype(str).str.replace(',', '', regex=True)
sales_df['Sales'] = pd.to_numeric(sales_df['Sales'], errors='coerce')

# Clean Discount column: remove percentage signs or non-numeric characters and convert to numeric
sales_df['Discount'] = sales_df['Discount'].astype(str).str.replace('%', '', regex=True)
sales_df['Discount'] = pd.to_numeric(sales_df['Discount'], errors='coerce')

# Convert Order_Date into appropriate Pandas datetime type
sales_df['Order_Date'] = pd.to_datetime(sales_df['Order_Date'], format='mixed')

# Check for missing values and handle them
numerical_cols = sales_df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    if sales_df[col].isnull().any():
        sales_df[col] = sales_df[col].fillna(sales_df[col].mean())

# B. Sales Analysis
total_sales = sales_df['Sales'].sum()
total_profit = sales_df['Profit'].sum()
avg_sales = sales_df['Sales'].mean()
top_5_products = sales_df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(5)
region_sales = sales_df.groupby('Region')['Sales'].sum()
highest_sales_region = region_sales.idxmax()

print("=== B. SALES ANALYSIS ===")
print(f"Total Sales: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Average Sales: ${avg_sales:,.2f}")
print("\nTop 5 Products based on Sales:")
print(top_5_products)
print(f"\nRegion generating the highest sales: {highest_sales_region} (${region_sales.max():,.2f})")

# C. Category Analysis
category_summary = sales_df.groupby('Category').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Average_Discount=('Discount', 'mean')
).sort_values(by='Total_Sales', ascending=False)

print("\n=== C. CATEGORY ANALYSIS ===")
display(category_summary)

# D. Business Insights
most_profitable_category = category_summary['Total_Profit'].idxmax()
top_product = sales_df.groupby('Product')['Sales'].sum().idxmax()

print("\n=== D. BUSINESS INSIGHTS ===")
print(f"1. Most profitable category: {most_profitable_category}")
print(f"2. Region with the highest sales: {highest_sales_region}")
print(f"3. Product with the highest sales: {top_product}")
print("\nObservations:")
print("  - Computers drive the most value, contributing the highest share of both overall sales and profit.")
print("  - The North region is our key geographic market, bringing in the highest sales volume.")
print("  - Profitability remains robust even when average discount rates vary across product categories.")

=== B. SALES ANALYSIS ===
Total Sales: $94,400.44
Total Profit: $15,245.17
Average Sales: $524.45

Top 5 Products based on Sales:
Product
Laptop        33995.0
Printer       13719.3
Tablet        10291.2
Monitor        9508.9
Headphones     5999.5
Name: Sales, dtype: float64

Region generating the highest sales: West ($37,314.18)

TypeError: agg function failed [how->mean,dtype->object]